# entities.py
#
# PURPOSE: Modularized entity system. Adversary now performs true trail-walking: moves stepwise from trail tile to adjacent trail tile; never locks on to player location; unsticks at dead ends.
# GENERATED BY: Layer 0035 (feature: adversary stepwise trail-walking, prevents stuck, no lock-on)
# LLM MODEL: GPT-4o (2024-06)

import random
from collections import deque
import logging

DIRECTIONS = [(1, 0), (-1, 0), (0, 1), (0, -1)]

def adjacent_tiles(x, y):
    for dx, dy in DIRECTIONS:
        yield (x + dx, y + dy)

class Trap:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.triggered = False
        logging.debug(f"Trap created at ({x}, {y})")

    def trigger(self):
        self.triggered = True
        logging.debug(f"Trap at ({self.x}, {self.y}) triggered.")

    def is_visible(self, debug):
        return debug or self.triggered

class Entity:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.trail = set()
        self.trail.add((x, y))
        self.explored = set()
        self.explored.add((x, y))
        logging.debug(f"{self.__class__.__name__} created at ({x}, {y})")

    def move(self, *args, **kwargs):
        raise NotImplementedError("Subclasses must implement the move method.")

class Player(Entity):
    """
    Player character entity. Maintains trail (set) and ordered trail_order (list).
    """
    def __init__(self, x, y, health=3, speed=1, vision_radius=3):
        super().__init__(x, y)
        self.health = health
        self.speed = speed
        self.vision_radius = vision_radius
        self.trail_order = [(x, y)]  # Ordered list of positions for adversary AI
        logging.debug(f"Player initialized at ({x}, {y}) with health={health}, speed={speed}, vision={vision_radius}")

    def move(self, dx, dy, game_map, is_open_tile):
        nx, ny = self.x + dx, self.y + dy
        if is_open_tile(game_map, nx, ny):
            self.x, self.y = nx, ny
            self.trail.add((self.x, self.y))
            self.explored.add((self.x, self.y))
            if (self.x, self.y) not in self.trail_order:
                self.trail_order.append((self.x, self.y))
            logging.debug(f"Player moved to ({self.x}, {self.y})")
            return True
        return False

    def take_damage(self, amount):
        self.health -= amount
        logging.debug(f"Player took {amount} damage, health now {self.health}")
        return self.health > 0

    def heal(self, amount):
        self.health = min(self.health + amount, 3)
        logging.debug(f"Player healed by {amount}, health now {self.health}")

class AdversaryBase(Entity):
    def __init__(self, x, y, vision_radius=2):
        super().__init__(x, y)
        self.mode = "explore"
        self.last_dir = (0, 0)
        self.in_hallway = False
        self.vision_radius = vision_radius
        self.alerted_player_pos = None
        logging.debug(f"AdversaryBase initialized at ({x}, {y}) with vision={vision_radius}")

    def move(self, *args, **kwargs):
        raise NotImplementedError("AdversaryBase is abstract.")

class Adversary(AdversaryBase):
    """
    Adversary: Performs true trail-walking, stepping to adjacent trail tiles;
    never locks onto player location; unsticks at dead ends.
    """

    def __init__(self, x, y, vision_radius=2):
        super().__init__(x, y, vision_radius)
        self.trail_direction = None  # Optional: can be used for smart forward/backward selection

    def alert_to_player_position(self, pos):
        self.alerted_player_pos = pos
        logging.debug(f"Adversary alerted to player position at {pos}")

    def move(self, game, player_trail, player_pos, is_floor, add_message):
        logging.debug(f"Adversary move called at ({self.x}, {self.y})")
        if self.alerted_player_pos is not None:
            if self._pursue_alerted_player_pos(game, is_floor):
                logging.debug("Adversary is pursuing alerted player position.")
                return
        if self.try_walk_trail(game, player_trail, is_floor):
            logging.debug("Adversary is walking the player trail.")
            return
        if self.try_follow_hallway(game, is_floor):
            logging.debug("Adversary is following hallway.")
            return
        if self.try_seek_hallway_frontier(game, is_floor):
            logging.debug("Adversary is seeking hallway frontier.")
            return
        if self.try_seek_general_frontier(game, is_floor):
            logging.debug("Adversary is seeking general frontier.")
            return
        self.step_randomly(game, is_floor)
        logging.debug("Adversary stepped randomly.")

    def try_walk_trail(self, game, player_trail, is_floor):
        """
        Stepwise trail-walking: If on a trail tile, step to an adjacent trail tile.
        At branches, pick randomly. Never locks onto the player.
        """
        # Only do this if the adversary can see trail tiles in its vision
        tiles_in_vision = set(tile for tile in self.tiles_in_vision()
                              if tile in player_trail and is_floor(game.map, *tile))
        if (self.x, self.y) not in tiles_in_vision:
            return False

        neighbors = [n for n in adjacent_tiles(self.x, self.y)
                     if n in player_trail and is_floor(game.map, *n)]
        if neighbors:
            # Optionally, prefer unexplored by adversary, otherwise random
            unexplored = [n for n in neighbors if n not in self.explored]
            next_tile = random.choice(unexplored) if unexplored else random.choice(neighbors)
            self.move_to(*next_tile)
            self.mode = "trail_walk"
            logging.debug(f"Adversary walks trail to {next_tile}")
            return True

        # No further steps on trail; at dead end
        return False

    def tiles_in_vision(self):
        for dx in range(-self.vision_radius, self.vision_radius + 1):
            for dy in range(-self.vision_radius, self.vision_radius + 1):
                yield (self.x + dx, self.y + dy)

    def _pursue_alerted_player_pos(self, game, is_floor):
        target = self.alerted_player_pos
        if (self.x, self.y) == target:
            self.alerted_player_pos = None
            logging.debug("Adversary arrived at alerted player position.")
            return False
        queue = deque([(self.x, self.y)])
        visited = set([(self.x, self.y)])
        prev = {}
        found = False
        while queue and not found:
            current = queue.popleft()
            for nx, ny in adjacent_tiles(*current):
                if (nx, ny) not in visited and is_floor(game.map, nx, ny):
                    visited.add((nx, ny))
                    prev[(nx, ny)] = current
                    if (nx, ny) == target:
                        found = True
                        break
                    queue.append((nx, ny))
        if found:
            step = target
            path = [step]
            while path[-1] != (self.x, self.y):
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "alerted_player_seek"
                logging.debug(f"Adversary moving toward alerted position, now at {path[1]}")
            else:
                self.alerted_player_pos = None
                return False
            return True
        else:
            self.alerted_player_pos = None
            return False

    # ---- Standard AI methods unchanged ----

    def try_follow_hallway(self, game, is_floor):
        if not self.is_in_hallway(game, is_floor):
            return False
        dx, dy = self.last_dir
        if (dx, dy) == (0, 0):
            for ndx, ndy in DIRECTIONS:
                next_pos = (self.x + ndx, self.y + ndy)
                if is_floor(game.map, *next_pos):
                    self.last_dir = (ndx, ndy)
                    self.move_to(*next_pos)
                    logging.debug(f"Adversary follows hallway to {next_pos}")
                    return True
            return False
        forward = (self.x + dx, self.y + dy)
        if is_floor(game.map, *forward):
            if forward != (self.x, self.y):
                self.move_to(*forward)
                logging.debug(f"Adversary continues forward in hallway to {forward}")
                return True
        for ndx, ndy in DIRECTIONS:
            if (ndx, ndy) == (-dx, -dy):
                continue
            next_pos = (self.x + ndx, self.y + ndy)
            if is_floor(game.map, *next_pos) and next_pos != (self.x, self.y):
                self.last_dir = (ndx, ndy)
                self.move_to(*next_pos)
                logging.debug(f"Adversary takes turn in hallway to {next_pos}")
                return True
        return False

    def is_in_hallway(self, game, is_floor, pos=None):
        x, y = pos if pos is not None else (self.x, self.y)
        wall_count = 0
        for neighbor in adjacent_tiles(x, y):
            if not is_floor(game.map, *neighbor):
                wall_count += 1
        return wall_count >= 2

    def try_seek_hallway_frontier(self, game, is_floor):
        start = (self.x, self.y)
        queue = deque([start])
        visited = set([start])
        prev = {}
        found_hallway = None
        while queue:
            current = queue.popleft()
            for neighbor in adjacent_tiles(*current):
                if neighbor in visited:
                    continue
                if not is_floor(game.map, *neighbor):
                    continue
                visited.add(neighbor)
                prev[neighbor] = current
                if neighbor not in self.explored and self.is_in_hallway(game, is_floor, pos=neighbor):
                    found_hallway = neighbor
                    break
                queue.append(neighbor)
            if found_hallway:
                break
        if found_hallway:
            path = [found_hallway]
            while path[-1] != start:
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "hallway_seek"
                logging.debug(f"Adversary seeks hallway frontier to {path[1]}")
                return True
        return False

    def try_seek_general_frontier(self, game, is_floor):
        start = (self.x, self.y)
        queue = deque([start])
        visited = set([start])
        prev = {}
        found_frontier = None
        while queue:
            current = queue.popleft()
            for neighbor in adjacent_tiles(*current):
                if neighbor in visited:
                    continue
                if not is_floor(game.map, *neighbor):
                    continue
                visited.add(neighbor)
                prev[neighbor] = current
                if neighbor not in self.explored:
                    found_frontier = neighbor
                    break
                queue.append(neighbor)
            if found_frontier:
                break
        if found_frontier:
            path = [found_frontier]
            while path[-1] != start:
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "frontier_seek"
                logging.debug(f"Adversary seeks general frontier to {path[1]}")
                return True
        return False

    def step_randomly(self, game, is_floor):
        neighbors = [n for n in adjacent_tiles(self.x, self.y) if is_floor(game.map, *n)]
        if not neighbors:
            logging.debug("Adversary is trapped, no valid moves.")
            return
        random.shuffle(neighbors)
        chosen = neighbors[0]
        logging.debug(f"step_randomly: moving from ({self.x}, {self.y}) to {chosen}")
        self.move_to(*chosen)
        self.mode = "explore"

    def move_to(self, x, y):
        self.last_dir = (x - self.x, y - self.y)
        self.x, self.y = x, y
        self.trail.add((x, y))
        self.explored.add((x, y))
        logging.debug(f"{self.__class__.__name__} moved to ({x}, {y})")
