# entities.py
#
# PURPOSE: Modularized entity system for game actors, with Adversary AI and support for noise trap alerts
# that allow the adversary to pursue the last known player position.
# GENERATED BY: Layer 0034 (feature: adversary pursues actual player location revealed by trap)
# LLM MODEL: GPT-4o (2024-06)

import random
from collections import deque
import logging

# Define the four directions for adjacent movement (up, down, left, right)
DIRECTIONS = [(1, 0), (-1, 0), (0, 1), (0, -1)]

def adjacent_tiles(x, y):
    """Yield coordinates of the four directly adjacent (up/down/left/right) tiles."""
    for dx, dy in DIRECTIONS:
        yield (x + dx, y + dy)

# ==== LAYER 34: Noise Trap Entity ====
class Trap:
    """
    Represents a noise trap on the dungeon map.
    Invisible unless in debug mode or triggered. Can be triggered multiple times.
    """
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.triggered = False

    def trigger(self):
        self.triggered = True

    def is_visible(self, debug):
        return debug or self.triggered

# ==== END LAYER 34 Trap ====

class Entity:
    """
    Abstract base class for all moving entities in the game.
    Tracks position, trail, and explored tiles.
    """
    def __init__(self, x, y):
        self.x = x
        self.y = y
        self.trail = set()
        self.trail.add((x, y))
        self.explored = set()
        self.explored.add((x, y))

    def move(self, *args, **kwargs):
        raise NotImplementedError("Subclasses must implement the move method.")

class Player(Entity):
    """
    Player character entity. Handles player movement, exploration tracking, and core attributes.
    """
    def __init__(self, x, y, health=3, speed=1, vision_radius=3):
        super().__init__(x, y)
        self.health = health
        self.speed = speed
        self.vision_radius = vision_radius

    def move(self, dx, dy, game_map, is_open_tile):
        nx, ny = self.x + dx, self.y + dy
        if is_open_tile(game_map, nx, ny):
            self.x, self.y = nx, ny
            self.trail.add((self.x, self.y))
            self.explored.add((self.x, self.y))
            return True
        return False

    def take_damage(self, amount):
        self.health -= amount
        return self.health > 0

    def heal(self, amount):
        self.health = min(self.health + amount, 3)

class AdversaryBase(Entity):
    """
    Base class for AI-controlled adversaries.
    Encapsulates shared properties and basic exploration logic.
    """
    def __init__(self, x, y, vision_radius=2):
        super().__init__(x, y)
        self.mode = "explore"
        self.last_dir = (0, 0)
        self.locked_on = False
        self.in_hallway = False
        self.vision_radius = vision_radius

    def move(self, *args, **kwargs):
        raise NotImplementedError("AdversaryBase is abstract.")

class Adversary(AdversaryBase):
    """
    Adversary: pursues the player by following their trail, navigating hallways,
    and prioritizes unexplored hallways, with support for 'last known player position'
    from noise trap alerts.
    """

    def __init__(self, x, y, vision_radius=2):
        super().__init__(x, y, vision_radius)
        self.alerted_player_pos = None  # LAYER 34: Last known player position from noise trap

    def alert_to_player_position(self, pos):
        """Called when the player triggers a noise trap. Remembers the exact location for pursuit."""
        self.alerted_player_pos = pos

    def move(self, game, player_trail, player_pos, is_floor, add_message):
        """
        Determines the adversary's next action. If an alert is set by a noise trap,
        pathfind to that location. Otherwise, use normal AI priorities.
        """
        # LAYER 34: Pursue last known player position if available
        if self.alerted_player_pos is not None:
            if self._pursue_alerted_player_pos(game, is_floor):
                return  # Still pursuing
            # If pursuit finished or failed, fall through to standard AI

        # ---- Standard AI priorities ----
        if self.try_lock_on_to_player(game, player_trail, player_pos, is_floor, add_message):
            return
        if self.try_follow_hallway(game, is_floor):
            return
        if self.try_seek_hallway_frontier(game, is_floor):
            return
        if self.try_seek_general_frontier(game, is_floor):
            return
        self.step_randomly(game, is_floor)

    def _pursue_alerted_player_pos(self, game, is_floor):
        """
        If there is an active alert from a trap, pathfind to the last known player position.
        Returns True if still pursuing, False if alert is cleared and AI should revert to normal.
        """
        target = self.alerted_player_pos
        if (self.x, self.y) == target:
            # Arrived: clear alert
            self.alerted_player_pos = None
            return False
        # Pathfind toward alerted player position using BFS
        queue = deque([(self.x, self.y)])
        visited = set([(self.x, self.y)])
        prev = {}
        found = False
        while queue and not found:
            current = queue.popleft()
            for nx, ny in adjacent_tiles(*current):
                if (nx, ny) not in visited and is_floor(game.map, nx, ny):
                    visited.add((nx, ny))
                    prev[(nx, ny)] = current
                    if (nx, ny) == target:
                        found = True
                        break
                    queue.append((nx, ny))
        if found:
            # Reconstruct path and move one step
            step = target
            path = [step]
            while path[-1] != (self.x, self.y):
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "alerted_player_seek"
            else:
                # Already at target; shouldn't get here due to check above
                self.alerted_player_pos = None
                return False
            return True  # Still pursuing
        else:
            # Can't reach target; clear alert and revert to normal AI
            self.alerted_player_pos = None
            return False

    # --- Standard AI logic from your existing code ---

    def try_lock_on_to_player(self, game, player_trail, player_pos, is_floor, add_message):
        if not self.can_see_player_trail(game, player_trail, is_floor):
            self.locked_on = False
            return False
        path = self.find_path_along_trail(game, player_trail, player_pos, is_floor)
        if path and len(path) > 1:
            if not self.locked_on:
                add_message("You feel a chill... something is following your trail!")
            self.locked_on = True
            self.move_to(*path[1])
            self.mode = "trail_follow"
            return True
        self.locked_on = False
        return False

    def can_see_player_trail(self, game, player_trail, is_floor):
        for tile in self.tiles_in_vision():
            if tile in player_trail and is_floor(game.map, *tile):
                return True
        return False

    def tiles_in_vision(self):
        for dx in range(-self.vision_radius, self.vision_radius + 1):
            for dy in range(-self.vision_radius, self.vision_radius + 1):
                yield (self.x + dx, self.y + dy)

    def find_path_along_trail(self, game, player_trail, player_pos, is_floor):
        start = (self.x, self.y)
        queue = deque([start])
        visited = set([start])
        prev = {}
        while queue:
            current = queue.popleft()
            if current == player_pos:
                path = [current]
                while path[-1] != start:
                    path.append(prev[path[-1]])
                path.reverse()
                return path
            for neighbor in adjacent_tiles(*current):
                if (neighbor not in visited and
                    neighbor in player_trail and
                    is_floor(game.map, *neighbor)):
                    visited.add(neighbor)
                    prev[neighbor] = current
                    queue.append(neighbor)
        return None

    def try_follow_hallway(self, game, is_floor):
        if not self.is_in_hallway(game, is_floor):
            return False

        dx, dy = self.last_dir
        if (dx, dy) == (0, 0):
            for ndx, ndy in DIRECTIONS:
                next_pos = (self.x + ndx, self.y + ndy)
                if is_floor(game.map, *next_pos):
                    self.last_dir = (ndx, ndy)
                    self.move_to(*next_pos)
                    return True
            return False
        forward = (self.x + dx, self.y + dy)
        if is_floor(game.map, *forward):
            if forward != (self.x, self.y):
                self.move_to(*forward)
                return True
        for ndx, ndy in DIRECTIONS:
            if (ndx, ndy) == (-dx, -dy):
                continue
            next_pos = (self.x + ndx, self.y + ndy)
            if is_floor(game.map, *next_pos) and next_pos != (self.x, self.y):
                self.last_dir = (ndx, ndy)
                self.move_to(*next_pos)
                return True
        return False

    def is_in_hallway(self, game, is_floor, pos=None):
        x, y = pos if pos is not None else (self.x, self.y)
        wall_count = 0
        for neighbor in adjacent_tiles(x, y):
            if not is_floor(game.map, *neighbor):
                wall_count += 1
        return wall_count >= 2

    def try_seek_hallway_frontier(self, game, is_floor):
        start = (self.x, self.y)
        queue = deque([start])
        visited = set([start])
        prev = {}
        found_hallway = None
        while queue:
            current = queue.popleft()
            for neighbor in adjacent_tiles(*current):
                if neighbor in visited:
                    continue
                if not is_floor(game.map, *neighbor):
                    continue
                visited.add(neighbor)
                prev[neighbor] = current
                if neighbor not in self.explored and self.is_in_hallway(game, is_floor, pos=neighbor):
                    found_hallway = neighbor
                    break
                queue.append(neighbor)
            if found_hallway:
                break
        if found_hallway:
            path = [found_hallway]
            while path[-1] != start:
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "hallway_seek"
                return True
        return False

    def try_seek_general_frontier(self, game, is_floor):
        start = (self.x, self.y)
        queue = deque([start])
        visited = set([start])
        prev = {}
        found_frontier = None
        while queue:
            current = queue.popleft()
            for neighbor in adjacent_tiles(*current):
                if neighbor in visited:
                    continue
                if not is_floor(game.map, *neighbor):
                    continue
                visited.add(neighbor)
                prev[neighbor] = current
                if neighbor not in self.explored:
                    found_frontier = neighbor
                    break
                queue.append(neighbor)
            if found_frontier:
                break
        if found_frontier:
            path = [found_frontier]
            while path[-1] != start:
                path.append(prev[path[-1]])
            path.reverse()
            if len(path) > 1:
                self.move_to(*path[1])
                self.mode = "frontier_seek"
                return True
        return False

    def step_randomly(self, game, is_floor):
        neighbors = [n for n in adjacent_tiles(self.x, self.y) if is_floor(game.map, *n)]
        if not neighbors:
            logging.debug("Adversary is trapped, no valid moves.")
            return
        random.shuffle(neighbors)
        chosen = neighbors[0]
        logging.debug(f"step_randomly: moving from ({self.x}, {self.y}) to {chosen}")
        self.move_to(*chosen)
        self.mode = "explore"

    def move_to(self, x, y):
        self.last_dir = (x - self.x, y - self.y)
        self.x, self.y = x, y
        self.trail.add((x, y))
        self.explored.add((x, y))
