# FILE: app/src/game.py
# PURPOSE: Main game logic with scalable noise traps. When player triggers a trap, adversary is alerted to that position and will pursue. Reveal (3 ticks) only on adversary-triggered trap. Immediate game-over on collision.
# GENERATED BY: Layer 0036 (fix: adversary pursues player trap triggers, only reveal on adversary trap trigger, collision bug fixed)
# LLM MODEL: GPT-4o (2024-06)

import os
import sys
import time
import json
from mapgen import generate_map, place_entity
from entities import Player, Adversary, Trap
from renderer import Renderer
from utils import get_terminal_size, is_open_tile, is_floor, load_config
from utils import setup_logger
import logging
import curses
import random

setup_logger()

class Game:
    def __init__(self, config):
        map_width = config["map_width"]
        map_height = config["map_height"]
        map_config = config.get("map_config", {})
        logging.info(
            f"Game start. Layer={config['LAYER']}, Map size={map_width}x{map_height}, Map config={map_config}"
        )
        self.map, (px, py), self.exit_pos = generate_map(map_width, map_height, map_config)
        self.layer = config["LAYER"]
        self.player = Player(px, py)
        self.messages = []
        self.running = True
        self.last_frame_time = time.time()
        self.fps = 0.0
        self.tick = 0

        self.seen = [[False for _ in range(map_width)] for _ in range(map_height)]
        self._reveal_visible_area()

        floor_tile = map_config.get("tileset", {}).get("floor", ".")
        occupied = {(px, py)}
        try:
            ax, ay = place_entity(self.map, occupied, floor_tile)
            self.adversary = Adversary(ax, ay)
            logging.info(f"Player spawned at ({px},{py}); Adversary spawned at ({ax},{ay}); Exit at {self.exit_pos}")
        except Exception as e:
            logging.error(f"Failed to place adversary: {e}")
            raise

        self.player_slow_counter = 0

        self.viewport_width, self.viewport_height = self._get_dynamic_viewport_size()
        self.renderer = Renderer(config)

        self.traps = self._place_noise_traps(
            config,
            min_traps=max(5, (map_width * map_height) // 50),
            max_traps=max(10, (map_width * map_height) // 25),
            exclude={(px, py), (ax, ay), self.exit_pos},
            floor_tile=floor_tile
        )

        self.adversary_reveal_counter = 0

    def _place_noise_traps(self, config, min_traps=5, max_traps=10, exclude=None, floor_tile='.'):
        traps = []
        exclude = set(exclude) if exclude else set()
        valid_tiles = [
            (x, y)
            for y, row in enumerate(self.map)
            for x, val in enumerate(row)
            if val == floor_tile and (x, y) not in exclude
        ]
        num_traps = random.randint(min_traps, max_traps) if valid_tiles else 0
        random.shuffle(valid_tiles)
        for pos in valid_tiles[:num_traps]:
            traps.append(Trap(*pos))
        logging.info(f"{len(traps)} noise traps placed (min={min_traps}, max={max_traps}, area={len(self.map)*len(self.map[0])}).")
        return traps

    def _get_dynamic_viewport_size(self):
        term_w, term_h = get_terminal_size()
        reserved_top = 1
        reserved_bottom = 3
        reserved_input = 1
        available_h = max(term_h - reserved_top - reserved_bottom - reserved_input, 1)
        vp_w = min(term_w, len(self.map[0]))
        vp_h = min(available_h, len(self.map))
        return vp_w, vp_h

    def run(self):
        curses.wrapper(self._curses_game_loop)

    def _curses_game_loop(self, stdscr):
        logging.info("Game loop started.")
        stdscr.nodelay(False)
        while self.running:
            frame_start = time.time()
            self.renderer.draw(
                stdscr, self, self.player, self.adversary, self.exit_pos,
                traps=self.traps,
                adversary_reveal=(self.adversary_reveal_counter > 0)
            )
            key = stdscr.getch()
            command = self._handle_input(self._convert_curses_key(key))

            # ==== Trap detection and triggering for player ====
            for trap in self.traps:
                if (self.player.x, self.player.y) == (trap.x, trap.y):
                    if not trap.triggered:
                        trap.trigger()
                        self.adversary.alert_to_player_position((self.player.x, self.player.y))
                        self._add_message("You’ve hit a noise trap. The adversary is coming for you!")

            # === Check for collision immediately after player move ===
            if (self.player.x, self.player.y) == (self.adversary.x, self.adversary.y):
                self._add_message("You lose! The adversary caught you!")
                logging.info("Game Over: Player caught by adversary (after player move).")
                self.renderer.draw(
                    stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps
                )
                stdscr.getch()
                break

            player_on_red_trail = (self.player.x, self.player.y) in self.adversary.trail
            if player_on_red_trail:
                if self.player_slow_counter == 0 and command:
                    self.player_slow_counter = 1
                    self._add_message("You are slowed by the adversary's trail!")
                elif self.player_slow_counter > 0:
                    self.player_slow_counter -= 1
                    command = False
                    self._add_message("You are slowed by the adversary's trail!")
            else:
                self.player_slow_counter = 0
            if command:
                self.player.trail.add((self.player.x, self.player.y))
                self.player.explored.add((self.player.x, self.player.y))
            self._reveal_visible_area()

            # === Adversary move, and check for trap triggers ===
            self.adversary.move(
                self, self.player.trail, (self.player.x, self.player.y), is_floor, self._add_message
            )

            # === Check for collision immediately after adversary move ===
            if (self.adversary.x, self.adversary.y) == (self.player.x, self.player.y):
                self._add_message("You lose! The adversary caught you!")
                logging.info("Game Over: Player caught by adversary (after adversary move).")
                self.renderer.draw(
                    stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps
                )
                stdscr.getch()
                break

            for trap in self.traps:
                if (self.adversary.x, self.adversary.y) == (trap.x, trap.y) and not trap.triggered:
                    trap.trigger()
                    self.adversary_reveal_counter = 3  # Reveal for 3 ticks
                    self._add_message("The adversary triggered a noise trap! Its location is revealed for 3 ticks.")

            if (self.player.x, self.player.y) == self.exit_pos:
                self._add_message("You found the exit! Congratulations!")
                logging.info("Game Over: Player reached the exit and won.")
                self.renderer.draw(
                    stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps
                )
                stdscr.getch()
                break

            if self.adversary_reveal_counter > 0:
                self.adversary_reveal_counter -= 1

            self.tick += 1
            frame_end = time.time()
            self._update_fps(frame_end - frame_start)

        logging.info(f"Game ended after {self.tick} ticks.")

    def _update_fps(self, frame_duration):
        self.fps = 1.0 / frame_duration if frame_duration > 0 else 0.0

    def _reveal_visible_area(self):
        px, py = self.player.x, self.player.y
        for dy in range(-2, 3):
            for dx in range(-2, 3):
                x = px + dx
                y = py + dy
                if 0 <= y < len(self.map) and 0 <= x < len(self.map[0]):
                    self.seen[y][x] = True

    def _convert_curses_key(self, key):
        if key in (ord('w'), ord('W'), curses.KEY_UP):
            return 'w'
        elif key in (ord('s'), ord('S'), curses.KEY_DOWN):
            return 's'
        elif key in (ord('a'), ord('A'), curses.KEY_LEFT):
            return 'a'
        elif key in (ord('d'), ord('D'), curses.KEY_RIGHT):
            return 'd'
        elif key in (ord('q'), ord('Q')):
            self.running = False
            self._add_message("Goodbye!")
            logging.info("User quit via Q key.")
            return False
        elif key == '':
            self._add_message("Invalid input! Use W/A/S/D to move, Q to quit.")
            logging.debug(f"Invalid input received (empty or non-movement key)")
            return False
        else:
            self._add_message("Invalid input! Use W/A/S/D to move, Q to quit.")
            logging.debug(f"Invalid input received: {key!r}")
            return False

    def _handle_input(self, command):
        dx, dy = 0, 0
        if command == 'w':
            dy = -1
        elif command == 's':
            dy = 1
        elif command == 'a':
            dx = -1
        elif command == 'd':
            dx = 1
        elif command == 'q':
            self.running = False
            self._add_message("Goodbye!")
            logging.info("User quit via Q key.")
            return False
        elif command == '':
            self._add_message("Invalid input! Use W/A/S/D to move, Q to quit.")
            logging.debug(f"Invalid input received (empty or non-movement key)")
            return False
        else:
            self._add_message("Invalid input! Use W/A/S/D to move, Q to quit.")
            logging.debug(f"Invalid input received: {command!r}")
            return False
        moved = self.player.move(dx, dy, self.map, is_open_tile)
        if moved:
            self.tick += 1
        else:
            self._add_message("You can't walk there.")
            logging.debug(f"Player move blocked: attempted ({dx}, {dy}) from ({self.player.x}, {self.player.y})")
        return moved

    def _add_message(self, msg):
        important = (
            "You are slowed by the adversary's trail!" in msg or
            "You lose!" in msg or
            "Congratulations" in msg or
            "Invalid input" in msg or
            "noise trap" in msg
        )
        if important:
            logging.info(f"Game message: {msg}")
        self.messages.append(msg)

def main():
    config = load_config()
    game = Game(config)
    game.run()

if __name__ == "__main__":
    main()
