

# FILE: app/src/game.py
# PURPOSE: Main game logic using config-driven messages, gameplay mechanics, and input handling.
# GENERATED BY: Layer 0038 (feature: extract character representations and system configuration to config.json)
# LLM MODEL: Claude Sonnet 4 (2025-01)

import os
import sys
import time
import json
from mapgen import generate_map, place_entity
from entities import Player, Adversary, Trap
from renderer import Renderer
from utils import get_terminal_size, is_open_tile, is_floor, load_config
from utils import setup_logger
import logging
import curses
import random

setup_logger()

class Game:
    """Main game class handling all game logic and state."""
    
    def __init__(self, config):
        self.config = config
        map_width = config["map_width"]
        map_height = config["map_height"]
        map_config = config.get("map_config", {})
        
        logging.info(
            f"Game start. Layer={config['LAYER']}, Map size={map_width}x{map_height}, Map config={map_config}"
        )
        
        self.map, (px, py), self.exit_pos = generate_map(map_width, map_height, map_config)
        self.layer = config["LAYER"]
        self.player = Player(px, py)
        self.messages = []
        self.running = True
        self.last_frame_time = time.time()
        self.fps = 0.0
        self.tick = 0

        self.seen = [[False for _ in range(map_width)] for _ in range(map_height)]
        self._reveal_visible_area()

        floor_tile = map_config.get("tileset", {}).get("floor", ".")
        occupied = {(px, py)}
        try:
            ax, ay = place_entity(self.map, occupied, floor_tile)
            self.adversary = Adversary(ax, ay)
            logging.info(f"Player spawned at ({px},{py}); Adversary spawned at ({ax},{ay}); Exit at {self.exit_pos}")
        except Exception as e:
            logging.error(f"Failed to place adversary: {e}")
            raise

        self.player_slow_counter = 0
        self.viewport_width, self.viewport_height = self._get_dynamic_viewport_size()
        self.renderer = Renderer(config)

        # Initialize traps using config-driven placement
        self.traps = self._place_noise_traps(config, exclude={(px, py), (ax, ay), self.exit_pos}, floor_tile=floor_tile)
        self.adversary_reveal_counter = 0

    def _place_noise_traps(self, config, exclude=None, floor_tile='.'):
        """Place noise traps using config-driven parameters."""
        traps = []
        exclude = set(exclude) if exclude else set()
        trap_config = config["gameplay"]["trap_placement"]
        
        valid_tiles = [
            (x, y)
            for y, row in enumerate(self.map)
            for x, val in enumerate(row)
            if val == floor_tile and (x, y) not in exclude
        ]
        
        # Calculate trap count using config ratios
        area = len(self.map) * len(self.map[0])
        min_traps = max(trap_config["min_absolute"], area // trap_config["min_ratio_divisor"])
        max_traps = max(trap_config["max_absolute"], area // trap_config["max_ratio_divisor"])
        
        num_traps = random.randint(min_traps, max_traps) if valid_tiles else 0
        random.shuffle(valid_tiles)
        
        for pos in valid_tiles[:num_traps]:
            traps.append(Trap(*pos))
            
        logging.info(f"{len(traps)} noise traps placed (min={min_traps}, max={max_traps}, area={area}).")
        return traps

    def _get_dynamic_viewport_size(self):
        """Calculate viewport size based on terminal dimensions."""
        term_w, term_h = get_terminal_size()
        reserved_top = 1
        reserved_bottom = 3
        reserved_input = 1
        available_h = max(term_h - reserved_top - reserved_bottom - reserved_input, 1)
        vp_w = min(term_w, len(self.map[0]))
        vp_h = min(available_h, len(self.map))
        return vp_w, vp_h

    def run(self):
        """Main game entry point."""
        curses.wrapper(self._curses_game_loop)

    def _curses_game_loop(self, stdscr):
        """Main game loop using curses for input and display."""
        logging.info("Game loop started.")
        stdscr.nodelay(False)
        
        while self.running:
            frame_start = time.time()
            self.renderer.draw(
                stdscr, self, self.player, self.adversary, self.exit_pos,
                traps=self.traps,
                adversary_reveal=(self.adversary_reveal_counter > 0)
            )
            
            key = stdscr.getch()
            command = self._handle_input(self._convert_curses_key(key))

            # Check for player trap triggers
            for trap in self.traps:
                if (self.player.x, self.player.y) == (trap.x, trap.y):
                    if not trap.triggered:
                        trap.trigger()
                        self.adversary.alert_to_player_position((self.player.x, self.player.y))
                        self._add_message("noise_trap_player")

            # Check for collision after player move
            if (self.player.x, self.player.y) == (self.adversary.x, self.adversary.y):
                self._add_message("defeat")
                logging.info("Game Over: Player caught by adversary (after player move).")
                self.renderer.draw(stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps)
                stdscr.getch()
                break

            # Handle trail slowdown mechanics
            self._handle_trail_slowdown(command)
            
            if command:
                self.player.trail.add((self.player.x, self.player.y))
                self.player.explored.add((self.player.x, self.player.y))
                
            self._reveal_visible_area()

            # Adversary move and trap detection
            self.adversary.move(
                self, self.player.trail, (self.player.x, self.player.y), is_floor, self._add_message
            )

            # Check for collision after adversary move
            if (self.adversary.x, self.adversary.y) == (self.player.x, self.player.y):
                self._add_message("defeat")
                logging.info("Game Over: Player caught by adversary (after adversary move).")
                self.renderer.draw(stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps)
                stdscr.getch()
                break

            # Check for adversary trap triggers
            for trap in self.traps:
                if (self.adversary.x, self.adversary.y) == (trap.x, trap.y) and not trap.triggered:
                    trap.trigger()
                    reveal_duration = self.config["entities"]["adversary"]["reveal_duration_ticks"]
                    self.adversary_reveal_counter = reveal_duration
                    self._add_message("noise_trap_adversary")

            # Check for victory condition
            if (self.player.x, self.player.y) == self.exit_pos:
                self._add_message("victory")
                logging.info("Game Over: Player reached the exit and won.")
                self.renderer.draw(stdscr, self, self.player, self.adversary, self.exit_pos, traps=self.traps)
                stdscr.getch()
                break

            # Update reveal counter
            if self.adversary_reveal_counter > 0:
                self.adversary_reveal_counter -= 1

            self.tick += 1
            frame_end = time.time()
            self._update_fps(frame_end - frame_start)

        logging.info(f"Game ended after {self.tick} ticks.")

    def _handle_trail_slowdown(self, command):
        """Handle player slowdown when on adversary trail."""
        gameplay_config = self.config["gameplay"]
        player_on_red_trail = (self.player.x, self.player.y) in self.adversary.trail
        
        if player_on_red_trail:
            if self.player_slow_counter == 0 and command:
                self.player_slow_counter = gameplay_config["trail_slowdown_duration"]
                self._add_message("trail_slowdown")
            elif self.player_slow_counter > 0:
                self.player_slow_counter -= 1
                command = False
                self._add_message("trail_slowdown")
        else:
            self.player_slow_counter = 0

    def _update_fps(self, frame_duration):
        """Update FPS calculation."""
        self.fps = 1.0 / frame_duration if frame_duration > 0 else 0.0

    def _reveal_visible_area(self):
        """Reveal tiles around player based on config vision radius."""
        px, py = self.player.x, self.player.y
        vision_radius = self.config["gameplay"]["player_vision_reveal_radius"]
        
        for dy in range(-vision_radius, vision_radius + 1):
            for dx in range(-vision_radius, vision_radius + 1):
                x = px + dx
                y = py + dy
                if 0 <= y < len(self.map) and 0 <= x < len(self.map[0]):
                    self.seen[y][x] = True

    def _convert_curses_key(self, key):
        """Convert curses key codes to game commands using config mappings."""
        input_config = self.config["input"]
        
        # Handle movement keys
        if key in (ord('w'), ord('W'), curses.KEY_UP):
            return 'w'
        elif key in (ord('s'), ord('S'), curses.KEY_DOWN):
            return 's'
        elif key in (ord('a'), ord('A'), curses.KEY_LEFT):
            return 'a'
        elif key in (ord('d'), ord('D'), curses.KEY_RIGHT):
            return 'd'
        elif key in (ord('q'), ord('Q')):
            self.running = False
            self._add_message("goodbye")
            logging.info("User quit via Q key.")
            return False
        elif key == '':
            self._add_message("invalid_input")
            logging.debug(f"Invalid input received (empty or non-movement key)")
            return False
        else:
            self._add_message("invalid_input")
            logging.debug(f"Invalid input received: {key!r}")
            return False

    def _handle_input(self, command):
        """Process game input commands."""
        dx, dy = 0, 0
        
        if command == 'w':
            dy = -1
        elif command == 's':
            dy = 1
        elif command == 'a':
            dx = -1
        elif command == 'd':
            dx = 1
        elif command == 'q':
            self.running = False
            self._add_message("goodbye")
            logging.info("User quit via Q key.")
            return False
        elif command == '':
            self._add_message("invalid_input")
            logging.debug(f"Invalid input received (empty or non-movement key)")
            return False
        else:
            self._add_message("invalid_input")
            logging.debug(f"Invalid input received: {command!r}")
            return False
            
        moved = self.player.move(dx, dy, self.map, is_open_tile)
        if moved:
            self.tick += 1
        else:
            self._add_message("cannot_walk")
            logging.debug(f"Player move blocked: attempted ({dx}, {dy}) from ({self.player.x}, {self.player.y})")
        return moved

    def _add_message(self, message_key):
        """Add a message to the game log using config message templates."""
        messages = self.config["ui"]["messages"]
        
        if message_key in messages:
            msg = messages[message_key]
        else:
            # Fallback for direct string messages (backward compatibility)
            msg = message_key
            
        important = any(keyword in msg for keyword in [
            "slowed", "lose", "Congratulations", "Invalid", "noise trap"
        ])
        
        if important:
            logging.info(f"Game message: {msg}")
        self.messages.append(msg)

def main():
    """Main entry point for the game."""
    config = load_config()
    game = Game(config)
    game.run()

if __name__ == "__main__":
    main()