# FILE: app/src/mapgen.py
# PURPOSE: Dungeon map generation using config-driven parameters, row-major output, and correct floor tile for placement.
# GENERATED BY: Layer 0038 (feature: extract character representations and system configuration to config.json)
# LLM MODEL: Claude Sonnet 4 (2025-01)

import random
import logging
from utils import load_config

def generate_map(width, height, map_config=None):
    """
    Generates a dungeon map and returns:
    - The map (2D list, row-major: map[y][x])
    - Player starting position (tuple)
    - Exit position (tuple)
    Uses options from map_config if provided, else config defaults.
    """
    # Load global config for fallback defaults
    global_config = load_config()
    config_defaults = global_config.get("map_config", {})
    
    # Merge provided map_config with global config defaults
    if map_config is None:
        map_config = config_defaults
    else:
        # Start with config defaults and override with provided values
        merged_config = config_defaults.copy()
        merged_config.update(map_config)
        map_config = merged_config

    def get_opt(key, fallback_value):
        return map_config.get(key, fallback_value)

    # Extract configuration values
    max_rooms = get_opt("max_rooms", 8)
    room_min_size = get_opt("room_min_size", 4)
    room_max_size = get_opt("room_max_size", 8)
    tileset = get_opt("tileset", {"wall": "#", "floor": "."})
    WALL = tileset.get("wall", "#")
    FLOOR = tileset.get("floor", ".")
    seed = get_opt("seed", None)

    # Handle seed configuration
    if seed is not None:
        random.seed(seed)
        logging.debug(f"Random seed explicitly set to {seed}")
    else:
        seed = random.randint(0, 2**32 - 1)
        random.seed(seed)
        logging.debug(f"No seed provided; using generated seed {seed}")

    logging.debug(
        f"Generating map: width={width}, height={height}, max_rooms={max_rooms}, "
        f"room_size=({room_min_size}-{room_max_size}), tileset={tileset}, seed={seed}"
    )

    class Room:
        """Represents a rectangular room in the dungeon."""
        
        def __init__(self, x, y, w, h):
            self.x1 = x
            self.y1 = y
            self.x2 = x + w
            self.y2 = y + h

        def center(self):
            """Return the center coordinates of the room."""
            cx = (self.x1 + self.x2) // 2
            cy = (self.y1 + self.y2) // 2
            return (cx, cy)

        def intersect(self, other):
            """Check if this room intersects with another room."""
            return (self.x1 <= other.x2 and self.x2 >= other.x1 and
                    self.y1 <= other.y2 and self.y2 >= other.y1)

    def create_empty_map(width, height):
        """Create a map filled with wall tiles."""
        return [[WALL for _ in range(height)] for _ in range(width)]

    def carve_room(dmap, room):
        """Carve out a room by setting tiles to floor."""
        for x in range(room.x1, room.x2):
            for y in range(room.y1, room.y2):
                dmap[x][y] = FLOOR

    def carve_h_tunnel(dmap, x1, x2, y):
        """Carve a horizontal tunnel between two x coordinates."""
        for x in range(min(x1, x2), max(x1, x2) + 1):
            dmap[x][y] = FLOOR

    def carve_v_tunnel(dmap, y1, y2, x):
        """Carve a vertical tunnel between two y coordinates."""
        for y in range(min(y1, y2), max(y1, y2) + 1):
            dmap[x][y] = FLOOR

    def find_room_floor(room, dmap):
        """Find a valid floor tile within a room."""
        candidates = [
            (x, y)
            for x in range(room.x1, room.x2)
            for y in range(room.y1, room.y2)
            if dmap[x][y] == FLOOR
        ]
        if candidates:
            return random.choice(candidates)
        return (room.x1, room.y1)

    # Generate the dungeon
    dmap = create_empty_map(width, height)
    rooms = []

    # Place rooms
    for i in range(max_rooms):
        w = random.randint(room_min_size, room_max_size)
        h = random.randint(room_min_size, room_max_size)
        x = random.randint(1, width - w - 1)
        y = random.randint(1, height - h - 1)
        new_room = Room(x, y, w, h)

        # Skip if room intersects with existing rooms
        if any(new_room.intersect(other) for other in rooms):
            logging.debug(f"Room {i+1}: Overlaps existing room, skipping placement.")
            continue
            
        carve_room(dmap, new_room)

        # Connect to previous room with tunnels
        if rooms:
            (prev_x, prev_y) = rooms[-1].center()
            (new_x, new_y) = new_room.center()
            if random.randint(0, 1) == 0:
                carve_h_tunnel(dmap, prev_x, new_x, prev_y)
                carve_v_tunnel(dmap, prev_y, new_y, new_x)
            else:
                carve_v_tunnel(dmap, prev_y, new_y, prev_x)
                carve_h_tunnel(dmap, prev_x, new_x, new_y)
                
        rooms.append(new_room)
        logging.debug(f"Room {i+1}: Placed at ({x},{y}) size {w}x{h}.")

    # Determine player start and exit positions
    if rooms:
        # Player starts in first room
        sx, sy = rooms[0].center()
        if dmap[sx][sy] != FLOOR:
            logging.warning("Player start not on floor, correcting.")
            sx, sy = find_room_floor(rooms[0], dmap)
            
        # Exit is in last room
        ex, ey = rooms[-1].center()
        if dmap[ex][ey] != FLOOR:
            logging.warning("Exit not on floor, correcting.")
            ex, ey = find_room_floor(rooms[-1], dmap)
            
        start_x, start_y = sx, sy
        exit_x, exit_y = ex, ey
    else:
        logging.error("No rooms were placed! Using fallback (1,1) for player/exit.")
        start_x = start_y = exit_x = exit_y = 1

    # Convert to row-major format (map[y][x])
    dmap_row_major = [[dmap[x][y] for x in range(len(dmap))] for y in range(len(dmap[0]))]

    logging.info(
        f"Map generation complete: {len(rooms)} rooms placed. "
        f"Player at ({start_x},{start_y}), exit at ({exit_x},{exit_y}), seed={seed}"
    )
    return dmap_row_major, (start_x, start_y), (exit_x, exit_y)

def place_entity(dmap, occupied=None, floor_tile=None):
    """
    Returns a random (x, y) coordinate on a floor tile that is not in occupied.
    
    Args:
        dmap: The game map (row-major: map[y][x])
        occupied: Set of positions that are already occupied
        floor_tile: The character representing floor tiles (uses config if None)
        
    Returns:
        Tuple (x, y) representing the entity position
        
    Raises:
        ValueError: If no valid tile is available
    """
    # Use config default if no floor_tile specified
    if floor_tile is None:
        config = load_config()
        floor_tile = config["map_config"]["tileset"]["floor"]
    
    height = len(dmap)
    width = len(dmap[0])
    occupied = occupied or set()
    
    floor_tiles = [
        (x, y)
        for y in range(height)
        for x in range(width)
        if dmap[y][x] == floor_tile and (x, y) not in occupied
    ]
    
    if not floor_tiles:
        logging.error("No available floor tiles for entity placement!")
        raise ValueError("No available floor tiles for entity placement!")
        
    pos = random.choice(floor_tiles)
    logging.debug(f"Entity placed at {pos} (floor_tile='{floor_tile}').")
    return pos

def print_map(dmap):
    """
    Print the map to console for debugging purposes.
    
    Args:
        dmap: The game map (row-major: map[y][x])
    """
    height = len(dmap)
    width = len(dmap[0])
    for y in range(height):
        line = ''.join(dmap[y][x] for x in range(width))
        print(line)