# FILE: app/src/renderer.py
# PURPOSE: Handles all rendering and symbol/color logic using config-driven character representations and colors.
# GENERATED BY: Layer 0038 (feature: extract character representations and system configuration to config.json)
# LLM MODEL: Claude Sonnet 4 (2025-01)

import curses
import logging
from utils import load_config

def render_player_stats_inline(player):
    """Render player stats using config format template."""
    config = load_config()
    stats_format = config["ui"]["stats_format"]
    return stats_format.format(
        health=player.health,
        speed=player.speed,
        vision_radius=player.vision_radius
    )

class Renderer:
    """Handles all game rendering using config-driven display settings."""
    
    def __init__(self, config):
        self.config = config
        self.last_viewport_edge = None
        
        # Cache frequently used config values
        self.characters = config["characters"]
        self.colors = config["colors"]
        self.ui = config["ui"]

    def draw(self, win, game, player, adversary, exit_pos, traps=None, adversary_reveal=False):
        """Main rendering method for the game display."""
        win.clear()
        self._setup_colors()

        height, width = win.getmaxyx()
        debug = self.config.get("debug", False)
        px, py = player.x, player.y
        vw, vh = game.viewport_width, game.viewport_height
        rows, cols = len(game.map), len(game.map[0])
        left = max(0, min(px - vw // 2, cols - vw))
        top = max(0, min(py - vh // 2, rows - vh))
        right = left + vw
        bottom = top + vh

        # Render UI overlay and stats
        self._render_overlay(win, game, player, width)
        self._render_stats(win, player, width)

        # Prepare trap visibility
        trap_vis = set()
        if traps:
            for trap in traps:
                if trap.is_visible(debug):
                    trap_vis.add((trap.x, trap.y))

        adversary_visible = adversary_reveal
        map_top = 2
        adv_in_view = False

        # Render map tiles
        adv_in_view = self._render_map(
            win, game, player, adversary, exit_pos, trap_vis,
            left, top, right, bottom, map_top, height, width,
            adversary_visible, debug
        )

        # Render offscreen adversary arrow if needed
        if adversary_reveal and not adv_in_view:
            self._render_offscreen_arrow(win, adversary, player, width, height, map_top, vh)

        # Render controls and messages
        self._render_controls(win, height, width)
        self._render_messages(win, game, height, width)

        win.refresh()

    def _setup_colors(self):
        """Initialize curses color pairs."""
        curses.start_color()
        curses.use_default_colors()
        curses.init_pair(self.colors["bold_red"], curses.COLOR_RED, -1)
        curses.init_pair(self.colors["green"], curses.COLOR_GREEN, -1)
        curses.init_pair(self.colors["trap"], curses.COLOR_YELLOW, -1)
        curses.init_pair(self.colors["alert"], curses.COLOR_MAGENTA, -1)
        curses.init_pair(self.colors["arrow"], curses.COLOR_RED, curses.COLOR_BLACK)

    def _render_overlay(self, win, game, player, width):
        """Render the top overlay with layer, tick, FPS, and position info."""
        overlay = self.ui["overlay_format"].format(
            layer=game.layer,
            tick=game.tick,
            fps=int(game.fps),
            x=player.x,
            y=player.y
        )
        win.addstr(0, 0, overlay[:width - 1])

    def _render_stats(self, win, player, width):
        """Render player stats line."""
        stats = render_player_stats_inline(player)
        win.addstr(1, 0, stats[:width - 1])

    def _render_map(self, win, game, player, adversary, exit_pos, trap_vis,
                   left, top, right, bottom, map_top, height, width,
                   adversary_visible, debug):
        """Render the game map with all entities and effects."""
        adv_in_view = False
        
        for y in range(top, min(bottom, top + height - 5)):
            for x in range(left, min(right, left + width)):
                visible = True if debug else game.seen[y][x]
                char, color = self.characters["empty"], 0
                coord = (x, y)

                # Layered rendering in priority order
                if visible and (x, y) == (player.x, player.y):
                    char = self.characters["player"]
                    color = self.colors["green"]
                elif ((visible or adversary_visible) and (x, y) == (adversary.x, adversary.y)):
                    char = self.characters["adversary"]
                    color = self.colors["bold_red"]
                    if left <= adversary.x < right and top <= adversary.y < bottom:
                        adv_in_view = True
                elif visible and (x, y) in trap_vis:
                    char = self.characters["trap"]
                    color = self.colors["trap"]
                elif visible and (x, y) == exit_pos:
                    char = self.characters["exit"]
                    color = self.colors["bold_red"]
                elif (adversary.alerted_player_pos is not None and
                      visible and (x, y) == adversary.alerted_player_pos):
                    char = self.characters["alert_marker"]
                    color = self.colors["alert"]
                elif visible and (x, y) in player.trail and game.map[y][x] == '.':
                    char = self.characters["trail_player"]
                    color = self.colors["green"]
                elif visible and (x, y) in adversary.trail and game.map[y][x] == '.':
                    char = self.characters["trail_adversary"]
                    color = self.colors["bold_red"]
                elif visible:
                    char = game.map[y][x]
                else:
                    char = self.characters["empty"]

                # Render the character
                if color:
                    try:
                        win.addstr(map_top + y - top, x - left, char, curses.color_pair(color))
                    except curses.error:
                        pass
                else:
                    try:
                        win.addstr(map_top + y - top, x - left, char)
                    except curses.error:
                        pass
        
        return adv_in_view

    def _render_offscreen_arrow(self, win, adversary, player, width, height, map_top, vh):
        """Render directional arrow when adversary is offscreen but revealed."""
        direction = adversary.direction_from_player((player.x, player.y))
        arrow_char = self.characters["direction_arrows"].get(direction, '?')
        
        mid_x = width // 2
        mid_y = (height - 5) // 2 + 2
        
        # Calculate arrow position based on direction
        if direction in ['N', 'NE', 'NW']:
            pos_y = map_top
        elif direction in ['S', 'SE', 'SW']:
            pos_y = min(height - 5 - 1, map_top + vh - 1)
        else:
            pos_y = mid_y
            
        if direction in ['W', 'NW', 'SW']:
            pos_x = 0
        elif direction in ['E', 'NE', 'SE']:
            pos_x = width - 2
        else:
            pos_x = mid_x
            
        try:
            win.addstr(pos_y, pos_x, arrow_char, 
                      curses.color_pair(self.colors["arrow"]) | curses.A_BOLD)
        except curses.error:
            pass

    def _render_controls(self, win, height, width):
        """Render control instructions."""
        control_line = self.ui["controls_text"]
        win.addstr(height - 3, 0, control_line[:width - 1])

    def _render_messages(self, win, game, height, width):
        """Render recent game messages."""
        recent_msgs = game.messages[-2:] if getattr(game, "messages", None) else []
        for i, msg in enumerate(recent_msgs):
            win.addstr(height - 2 + i, 0, msg[:width - 1])
        for i in range(2 - len(recent_msgs)):
            win.addstr(height - 2 + len(recent_msgs) + i, 0, " " * (width - 1))